app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/dao-movie-db
      username: Alex
      password: alex
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always